services:
  latex:
    build:
      context: .
      dockerfile: Containerfile
    working_dir: /workspace
    volumes:
      - ./template:/workspace/template
    stdin_open: true
    tty: true
    command: sleep infinity